<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>KeycloakAuthZ.Caching</PackageId>
		<Version>0.1.2</Version>
		<Authors>Aleshin Yaroslav</Authors>
		<Description>Services for easy permission caching setup with IDistributedCache</Description>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<OutputType>Library</OutputType>
		<DebugType>portable</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
		<DebugSymbols>true</DebugSymbols>
		<CopyDebugSymbolFilesFromPackages>true</CopyDebugSymbolFilesFromPackages>
		<CopyDocumentationFilesFromPackages>true</CopyDocumentationFilesFromPackages>
		<PackageProjectUrl>https://github.com/YaroslavkaPizza/KeycloakAuthZCaching</PackageProjectUrl>
		<!-- Ссылка непосредственно на репозиторий -->
		<RepositoryUrl>https://github.com/YaroslavkaPizza/KeycloakAuthZCaching.git</RepositoryUrl>
		<!-- Тип репозитория (помогает NuGet понять, как с ним работать) -->
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.*-*" />
		<PackageReference Include="Keycloak.AuthServices.Authentication" Version="2.7.0" />
		<PackageReference Include="Keycloak.AuthServices.Authorization" Version="2.7.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0-*"/>
		<!--<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0-*" PrivateAssets="All"/>-->
	</ItemGroup>

	<PropertyGroup>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<!-- Включаем файл в пакет, чтобы NuGet его увидел -->
		<None Include="README.md" Pack="true" PackagePath="\"/>
	</ItemGroup>
</Project>
